public  class TeaTime {
    // Get Utensils and Ingredients
    // Boil water in a tea kettle
    // Make tea in Teaspot
    // add tea and sugar to a teacup
    // serve tea to friend

    // Get Utensils and Ingredients
    //  Get TeaCup
    //  Get Spoon
    //  Get Tea Kettle
    //  Get Tea
    //  Get Sugar
    //  Get Water

    // Boil water in a Tea Kettle
    //  Fill Kettle with Water
    //  Switch Kettle on
    //  Wait for Kettle to boil

    // Make Team in Teapot
    //  Put team in Teapot
    //  Put boiling water in Teapot
    //  Wait 2 minutes

    // Add Tea and Sugar to Teacup
    //   Pour Tea in Teacup
    //   Put 1 teaspoon of Sugar in Teacup
    //   Stir Tea in Teacup

    // Serve Tea to a Friend
    
    public TeaTime() {

    }
}
